# Generated by Django 4.1 on 2022-08-16 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Camper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('cabin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bunknotes.cabin')),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bunknotes.family')),
            ],
        ),
        migrations.CreateModel(
            name='tx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bunknotes.family')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bunknotes.sender')),
            ],
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('isDelivered', models.BooleanField()),
                ('date', models.DateField()),
                ('camper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bunknotes.camper')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bunknotes.sender')),
            ],
        ),
        migrations.AddField(
            model_name='camper',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bunknotes.family'),
        ),
    ]
