# Generated by Django 4.1 on 2022-08-16 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bunknotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='tx',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bunknotes.tx'),
            preserve_default=False,
        ),
    ]
